### ISSUE TITLE
Config `file_regex` should be required?

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-universal-file#27]
I didn't set a file_regex but it looks like it's required? 

```

visch@DESKTOP-9BDPA9T:~/git/tap-file$ meltano invoke tap-universal-file
2023-07-12T02:48:39.076764Z [info     ] Environment 'test' is active
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Catalog discovery failed: command ['/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/bin/tap-universal-file', '--config', '/home/visch/git/tap-file/.meltano/run/tap-universal-file/tap.8eff831a-973c-48ec-ab97-cbb882458af6.config.json', '--discover'] returned 1 with stderr:
 Traceback (most recent call last):
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/bin/tap-universal-file", line 8, in <module>
    sys.exit(TapUniversalFile.cli())
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/click/core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
  File "/home/visch/git/tap-file/tap_universal_file/tap.py", line 333, in cb_discover
    tap = cls(
  File "/home/visch/git/tap-file/tap_universal_file/tap.py", line 390, in __init__
    self.mapper.register_raw_streams_from_catalog(self.catalog)
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 167, in catalog
    self._catalog = self.input_catalog or self._singer_catalog
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 311, in _singer_catalog
    for stream in self.streams.values()
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 129, in streams
    for stream in self.load_streams():
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 344, in load_streams
    for stream in self.discover_streams():
  File "/home/visch/git/tap-file/tap_universal_file/tap.py", line 305, in discover_streams
    return [streams.DelimitedStream(self, name=name)]
  File "/home/visch/git/tap-file/tap_universal_file/client.py", line 45, in __init__
    super().__init__(tap, schema, name)
  File "/home/visch/git/tap-file/.meltano/extractors/tap-universal-file/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 165, in __init__
    if not self.schema:
  File "/home/visch/.pyenv/versions/3.8.16/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/visch/git/tap-file/tap_universal_file/client.py", line 82, in schema
    properties = self.get_properties()
  File "/home/visch/git/tap-file/tap_universal_file/streams.py", line 49, in get_properties
    for reader, _, _ in self._get_readers():
  File "/home/visch/git/tap-file/tap_universal_file/streams.py", line 78, in _get_readers
    for file in self.fs_manager.get_files(self.starting_replication_key_value):
  File "/home/visch/git/tap-file/tap_universal_file/files.py", line 140, in get_files
    raise RuntimeError(msg)
RuntimeError: No files found. Choose a different `filepath` or try a more lenient `file_regex`.
```

**Comment by sebastianswms** [comment]
Can't reproduce this. file_regex is only used if set. See https://github.com/MeltanoLabs/tap-universal-file/blob/main/tap_universal_file/files.py#L104-L108
